### ISSUE TITLE
need to catch error when serial port write failes 

### ISSUE THREAD

**Issue by AJ6CU** [AJ6CU/uBITX-Settings-Editor#14]
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\markj\Documents\GitHub\uBITX-EEPROM-Manager\uBITX_Settings_Editor\outputProcessor.py", line 43, in reset_ubitx
    self.RS232.write(bytes([magic1, magic2, magic3, magic4, WRITECOMMAND]))
  File "C:\Users\markj\Documents\GitHub\uBITX-EEPROM-Manager\uBITX_Settings_Editor\venv\Lib\site-packages\serial\serialwin32.py", line 317, in write
    raise SerialException("WriteFile failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: WriteFile failed (PermissionError(13, 'Access is denied.', None, 5))

**Comment by AJ6CU** [comment]
and need to time out on opens.

**Comment by AJ6CU** [comment]
fixed in beta 2 rework of com port processing
